import{i as c,S as i}from"./assets/vendor-0fc460d7.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const o of e.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function n(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(t){if(t.ep)return;t.ep=!0;const e=n(t);fetch(t.href,e)}})();const u=s=>{const a=document.querySelector(".gallery"),n=s.hits.map(r=>`<li class="gallery-item"><a href="${r.largeImageURL}" class="gallery-link"><img src="${r.webformatURL}"
      alt="${r.tags}" class="gallery-img"></a>
    <div class="card-content">
    <div class="label-cont"><span class="label">Likes</span><span class="value">${r.likes}</span></div>
    <div class="label-cont"><span class="label">Views</span><span class="value">${r.views}</span></div>
    <div class="label-cont"><span class="label">Comments</span><span class="value">${r.comments}</span>
    </div>
    <div class="label-cont"><span class="label">Downloads</span><span
        class="value">${r.downloads}</span></div>
  </div>
</li>`).join("");a.insertAdjacentHTML("beforeend",n)},p=s=>{s.preventDefault();const n={key:"43212506-95870309335e8ebf3ea9c8656",q:s.srcElement.elements.search_input.value,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9},t=`https://pixabay.com/api/?${new URLSearchParams(n).toString()}`;fetch(t).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0){c.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ff3333",position:"topRight"});return}u(e)}).catch(e=>e)},l={searchForm:document.querySelector(".search-form"),searchInput:document.querySelector(".search-input"),searchButton:document.querySelector(".search-button"),gallery:document.querySelector(".gallery")};l.searchForm.addEventListener("submit",p);const d=s=>{s.preventDefault(),s.target!==s.currentTarget&&new i(".gallery a")};l.gallery.addEventListener("click",d);
//# sourceMappingURL=commonHelpers.js.map
